#pragma once
#include "GameObject.h"
#include "ComponentEssentials.h"
#include "../Ice Climber Clone/IntroCamera.h"
#include "../Ice Climber Clone/LevelCamera.h"
#include "../Ice Climber Clone/Enemy.h"
#include "../Ice Climber Clone/Nitpicker.h"
#include "../Ice Climber Clone/Topi.h"
#include "../Ice Climber Clone/Hammer.h"
#include "../Ice Climber Clone/PlayerBehaviour.h"
#include "../Ice Climber Clone/BonusTimer.h"
#include "../Ice Climber Clone/Counter.h"
#include "../Ice Climber Clone/GameOverUI.h"
#include "../Ice Climber Clone/IceClimberButton.h"
#include "../Ice Climber Clone/LifeUI.h"
#include "../Ice Climber Clone/Cloud.h"
#include "../Ice Climber Clone/Debris.h"
#include "../Ice Climber Clone/ScoreScreenController.h"